# General
name: Minimal-Block
description: "Minimalistic, friendly, responsive."
url: http://localhost:4000

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: yourusername
twitter: yourusername
github: yourusername
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"